version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: adnanrahic/express-docker-app:test
    environment:
      - LOGS_ENABLED=true
      - LOGS_TOKEN=e4093a01-2600-4bfa-8833-e7a67717f885 
      - LOGS_RECEIVER_URL=https://logs-token-receiver.apps.test.sematext.com
      - EVENTS_RECEIVER_URL=https://event-receiver.apps.test.sematext.com
      # - LOGS_DESTINATION=logsene
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=APP]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
    ports:
      - "80:3000"
  
  st-logagent: 
    image: 'sematext/logagent:test'
    environment: 
      - LOGS_ENABLED_DEFAULT=false
      - LA_CONFIG_OVERRIDE=true

      # - LOGS_RECEIVER_URL=https://logs-token-receiver.apps.test.sematext.com 
      # - EVENTS_RECEIVER_URL=https://event-receiver.apps.test.sematext.com
    
      # - INFRA_TOKEN=31a70ed1-932c-4e8b-bcd4-cdb2ceb37ee9
      # - MONITORING_TOKEN=1db11262-9790-4910-8abc-9068c167a25d
      # - SPM_RECEIVER_URL=https://metrics-receiver.apps.test.sematext.com/receiver/v1
      # - SPM_LOG_TO_CONSOLE=true
      # - SPM_LOG_LEVEL=info
    deploy:
      mode: global
    cap_add: 
      - SYS_ADMIN  
    restart: always 
    volumes: 
      - '/var/run/docker.sock:/var/run/docker.sock' 

